# Generated by Django 5.2.7 on 2026-02-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('web-development', 'Web Development'), ('python', 'Python Development'), ('data-analyst', 'Data Analyst'), ('ui-ux', 'UI/UX Design')], max_length=50)),
                ('duration', models.CharField(choices=[('30', '30 Days'), ('45', '45 Days')], max_length=10)),
                ('college', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
